/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#e3beb8",
        "tertiary-fixed": "#ffdbca",
        "surface-dim": "#dbdad5",
        "inverse-surface": "#30312e",
        "primary": "#271310",
        "on-primary-fixed": "#2b1613",
        "primary-fixed": "#ffdad4",
        "primary-container": "#3e2723",
        "surface-container-high": "#eae8e3",
        "tertiary-container": "#47240f",
        "on-secondary-fixed": "#121e11",
        "on-tertiary-fixed-variant": "#653d26",
        "background": "#fbf9f4",
        "on-surface": "#1b1c19",
        "on-error": "#ffffff",
        "secondary": "#546251",
        "on-error-container": "#93000a",
        "on-surface-variant": "#504442",
        "surface-variant": "#e4e2dd",
        "outline-variant": "#d3c3c0",
        "outline": "#827472",
        "on-secondary-container": "#596655",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d8e7d1",
        "on-tertiary-container": "#bd896d",
        "surface-container": "#f0eee9",
        "surface": "#fbf9f4",
        "secondary-fixed-dim": "#bccbb5",
        "surface-bright": "#fbf9f4",
        "inverse-primary": "#e3beb8",
        "inverse-on-surface": "#f2f1ec",
        "surface-tint": "#745853",
        "on-primary-container": "#ae8d87",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container-highest": "#e4e2dd",
        "on-secondary-fixed-variant": "#3d4a3a",
        "tertiary-fixed-dim": "#f4ba9c",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-background": "#1b1c19",
        "secondary-container": "#d5e4ce",
        "tertiary": "#2e1001",
        "on-primary-fixed-variant": "#5b403c",
        "on-tertiary-fixed": "#311302",
      },
      fontFamily: {
        sans: ["Outfit", "sans-serif"],
      },
      fontSize: {
        "display-mobile": ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-desktop": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      spacing: {
        "section-gap": "80px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
  ],
};
